//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package  com.Tutorial{
	import org.flixel.*;
	
	public class MapBase {
		//Layer name definitions
		public static const LAYER_TILESHADOW:uint = 0;
		public static const LAYER_MAINLAYER:uint = 1;
		public static const LAYER_NEARBKGRND:uint = 2;
		public static const LAYER_FARBKGRND:uint = 3;

		//Layer variable accessors
		public var layerTileShadow:FlxTilemap;
		public var layerMainLayer:FlxTilemap;
		public var layerNearBkgrnd:FlxTilemap;
		public var layerFarBkgrnd:FlxTilemap;

		//Map layers and principal layer (map) declaration
		public var allLayers:Array;

		public var mainLayer:FlxTilemap;

		public var boundsMinX:int;
		public var boundsMinY:int;
		public var boundsMaxX:int;
		public var boundsMaxY:int;
		
		//Char ads
		public var playerStart:FlxPoint;
		public var spriteGroup:FlxGroup;

		public function MapBase() { }

		public var bgColor:uint = 0xff000000;

		virtual public function addSpritesToLayerTileShadow(onAddCallback:Function = null):void { }
		virtual public function addSpritesToLayerMainLayer(onAddCallback:Function = null):void { }
		virtual public function addSpritesToLayerNearBkgrnd(onAddCallback:Function = null):void { }
		virtual public function addSpritesToLayerFarBkgrnd(onAddCallback:Function = null):void { }

		public var customValues:Object = new Object;		//Name-value map;
		virtual public function customFunction(param:* = null):* { }

	}
}
