//Code generated by Flan. http://www.tbam.com.ar/utility--flan.php

package  com.Tutorial{
	import org.flixel.*;
	
	public class MapLevel1 extends MapBase {
		//Media content declarations
		[Embed(source="../../data/MapCSV_Level1_TileShadow.txt", mimeType="application/octet-stream")] public var CSV_TileShadow:Class;
		[Embed(source="../../data/TileShadows.png")] public var Img_TileShadow:Class;
		[Embed(source="../../data/MapCSV_Level1_MainLayer.txt", mimeType="application/octet-stream")] public var CSV_MainLayer:Class;
		[Embed(source="../../data/Tiles.png")] public var Img_MainLayer:Class;
		[Embed(source="../../data/MapCSV_Level1_NearBkgrnd.txt", mimeType="application/octet-stream")] public var CSV_NearBkgrnd:Class;
		[Embed(source="../../data/TreeBkgrnd.png")] public var Img_NearBkgrnd:Class;
		[Embed(source="../../data/MapCSV_Level1_FarBkgrnd.txt", mimeType="application/octet-stream")] public var CSV_FarBkgrnd:Class;
		[Embed(source="../../data/Tiles.png")] public var Img_FarBkgrnd:Class;

		
		public function MapLevel1() {

			_setCustomValues();
			spriteGroup = new FlxGroup();

			bgColor = 0xff909090;

			layerTileShadow = new FlxTilemap();// new CSV_TileShadow, Img_TileShadow, 14, 0);
			layerTileShadow.loadMap(new CSV_TileShadow, Img_TileShadow, 12, 12);
			layerTileShadow.collideIndex = 60;
			layerTileShadow.drawIndex = 1;
			layerTileShadow.x = 0;
			layerTileShadow.y = 0;
			layerTileShadow.scrollFactor.x = 1.000000;
			layerTileShadow.scrollFactor.y = 1.000000;
			
			layerMainLayer = new FlxTilemap();//new CSV_MainLayer, Img_MainLayer,1,1);
			layerMainLayer.loadMap(new CSV_MainLayer, Img_MainLayer, 12, 12);
			layerMainLayer.collideIndex = 1;
			layerMainLayer.drawIndex = 1;
			layerMainLayer.x = 0;
			layerMainLayer.y = 0;
			layerMainLayer.scrollFactor.x = 1.000000;
			layerMainLayer.scrollFactor.y = 1.000000;
			
			layerNearBkgrnd = new FlxTilemap();//new CSV_NearBkgrnd, Img_NearBkgrnd,1,1);
			layerNearBkgrnd.loadMap(new CSV_NearBkgrnd, Img_NearBkgrnd, 12, 12);
			layerNearBkgrnd.collideIndex = 60;
			layerNearBkgrnd.x = 0;
			layerNearBkgrnd.y = 0;
			layerNearBkgrnd.scrollFactor.x = 0.800000;
			layerNearBkgrnd.scrollFactor.y = 0.900000;
			
			layerFarBkgrnd = new FlxTilemap();//new CSV_FarBkgrnd, Img_FarBkgrnd,1,1);
			layerFarBkgrnd.loadMap(new CSV_FarBkgrnd, Img_FarBkgrnd, 12, 12);
			layerFarBkgrnd.collideIndex = 60;
			layerFarBkgrnd.drawIndex = 1;
			layerFarBkgrnd.x = 0;
			layerFarBkgrnd.y = 0;
			layerFarBkgrnd.scrollFactor.x = 0.500000;
			layerFarBkgrnd.scrollFactor.y = 0.750000;

			allLayers = [ layerTileShadow, layerMainLayer, layerNearBkgrnd, layerFarBkgrnd ];

			mainLayer = layerMainLayer;

			boundsMinX = 0;
			boundsMinY = 0;
			boundsMaxX = 1200;
			boundsMaxY = 960;
		}

		override public function addSpritesToLayerTileShadow(onAddCallback:Function = null):void {
			
			
			playerStart = new FlxPoint(19, 941);
			
			var obj:Sign;
			obj = new Sign(168, 932);
			obj.setMessage("Press 'X' to jump.");
			spriteGroup.add(obj);
			
			obj = new Sign(510, 932);
			obj.setMessage("Hold 'X' to jump Higher.");
			spriteGroup.add(obj);
			
			obj = new Sign(1062, 932);
			obj.setMessage("Jump onto a wall, then press 'X' to jump off it.");
			spriteGroup.add(obj);
			
			obj = new Sign(976, 752);
			obj.setMessage("Hold 'X' To hover while in the air.");
			spriteGroup.add(obj);
			
			obj = new Sign(236, 404);
			obj.setMessage("Collect pickups.");
			spriteGroup.add(obj);
			
			obj = new Sign(1095, 404);
			obj.setMessage("Go into the end-level thingy.");
			spriteGroup.add(obj);
		}

		override public function addSpritesToLayerNearBkgrnd(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new BackgroundDetail(224, 794, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(375, 738, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(570, 794, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(624, 709, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(817, 818, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(869, 703, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(1040, 770, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(1028, 494, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(764, 480, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(734, 605, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(520, 517, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(379, 542, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			FlxG.state.add(obj);
			if(onAddCallback != null)
				onAddCallback(obj);
			obj = new BackgroundDetail(258, 519, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(45, 493, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(108, 300, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(449, 323, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(273, 311, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(260, 649, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(752, 328, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(990, 413, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(1055, 276, 64);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.800000;
			obj.scrollFactor.y = 0.900000;
			spriteGroup.add(obj);
			
		}

		override public function addSpritesToLayerFarBkgrnd(onAddCallback:Function = null):void {
			var obj:FlxSprite;
			
			obj = new BackgroundDetail(853, 776, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(676, 728, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(526, 602, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(319, 730, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(300, 562, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(312, 370, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(115, 549, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(42, 744, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(522, 152, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(658, 405, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
			obj = new BackgroundDetail(872, 281, 128);;
			obj.x+=obj.offset.x;
			obj.y+=obj.offset.y;
			obj.scrollFactor.x = 0.500000;
			obj.scrollFactor.y = 0.750000;
			spriteGroup.add(obj);
			
		}

		override public function customFunction(param:* = null):* {

		}

		private function _setCustomValues():void {
		}

	}
}
